# -*- coding: utf-8 -*-
"""Sales Summary from a Tiny SQLite Database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZ15gISny6CZUXj1hA-Qv_ThKVSgwaoO
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connect to (or create) the database file
conn = sqlite3.connect("sales_data.db")

# Create a cursor
cursor = conn.cursor()

# Create a simple sales table
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

# Insert sample data
sample_data = [
    ('Laptop', 5, 800),
    ('Laptop', 3, 800),
    ('Phone', 10, 300),
    ('Phone', 7, 300),
    ('Tablet', 4, 400),
    ('Tablet', 2, 400)
]

cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)

# Commit changes
conn.commit()

# Write a SQL query to summarize total quantity and total revenue per product
query = """
SELECT
    product,
    SUM(quantity) AS total_quantity,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

# Run the query and load results into a DataFrame
df = pd.read_sql_query(query, conn)

# Display the summary
print(df)

# Plot revenue per product
df.plot(kind='bar', x='product', y='revenue', legend=False)
plt.title("Revenue by Product")
plt.ylabel("Revenue ($)")
plt.xlabel("Product")
plt.xticks(rotation=0)
plt.show()

plt.savefig("sales_chart.png")

from google.colab import files
files.download("sales_chart.png")